module:
  block: 0
  breakpoint: 0
  config: 0
  dblog: 0
  entity_reference: 0
  field: 0
  file: 0
  filter: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  page_cache: 0
  path: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views: 0
  views_ui: 0
  minimal: 1000
theme:
  classy: 0
  seven: 0
  bartik: 0
